package jesper_search.mapper;

import java.util.List;
import jesper_search.bean.Hotel;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface HotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dvb_hotel
     *
     * @mbggenerated Mon May 14 11:54:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dvb_hotel
     *
     * @mbggenerated Mon May 14 11:54:16 CST 2018
     */
    int insert(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dvb_hotel
     *
     * @mbggenerated Mon May 14 11:54:16 CST 2018
     */
    Hotel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dvb_hotel
     *
     * @mbggenerated Mon May 14 11:54:16 CST 2018
     */
    List<Hotel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dvb_hotel
     *
     * @mbggenerated Mon May 14 11:54:16 CST 2018
     */
    int updateByPrimaryKey(Hotel record);
}